name: todo
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any


  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  animated_custom_dropdown: ^3.0.0
  easy_date_timeline: ^1.0.3
  firebase_auth: ^4.16.0
  firebase_core: ^2.24.2
  flutter_easyloading: ^3.0.5
  bot_toast: ^4.1.3
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/
  fonts:
    - family: "Poppins"
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
