// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdB7lvnHbCvG7gbd5oLy3KsGkPJH6DC4I',
    appId: '1:845995762961:web:63cfe23e1fd17c3ea798b0',
    messagingSenderId: '845995762961',
    projectId: 'todo-f9858',
    authDomain: 'todo-f9858.firebaseapp.com',
    storageBucket: 'todo-f9858.appspot.com',
    measurementId: 'G-SXHLS5NTRX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV1jGhyowCnYZbziIiIJ9cejUXOmKtkJo',
    appId: '1:845995762961:android:692692c6bebfaacfa798b0',
    messagingSenderId: '845995762961',
    projectId: 'todo-f9858',
    storageBucket: 'todo-f9858.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYccQuLeujVRWSou0nMHafvPQuZKvI-v0',
    appId: '1:845995762961:ios:56bd574d2d8247a7a798b0',
    messagingSenderId: '845995762961',
    projectId: 'todo-f9858',
    storageBucket: 'todo-f9858.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYccQuLeujVRWSou0nMHafvPQuZKvI-v0',
    appId: '1:845995762961:ios:f68ec0bf84731b90a798b0',
    messagingSenderId: '845995762961',
    projectId: 'todo-f9858',
    storageBucket: 'todo-f9858.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
